In [1]:
#working with requests
import requests

In [2]:
URL="https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)

In [3]:
res

In [4]:
json_data=res.json()

In [5]:
import pandas as pd
df=pd.json_normalize(json_data["data"])
df=df[['id','Year','Title','ISBN']]
df

    id  Year            Title                  ISBN
0    1  1974           Carrie     978-0-385-08695-0
1    2  1975      Salem's Lot     978-0-385-00751-1
2    3  1977      The Shining     978-0-385-12167-5
3    4  1977             Rage     978-0-451-07645-8
4    5  1978        The Stand     978-0-385-12168-2
..  ..   ...              ...                   ...
59  60  2018        Elevation     978-1-98210-231-9
60  61  2019    The Institute     978-1-98211-056-7
61  62  2021            Later     978-1-78909-649-1
62  63  2021    Billy Summers     978-1-982-17361-6
63  72  1979  The Roopak Zone  978-0-670-26069697-5

[64 rows x 4 columns]

In [6]:
url="https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions.json"
response=requests.get(url)

In [7]:
response

In [8]:
json=response.json()

In [9]:
df=pd.json_normalize(json.values())
df=df[['author','language','source']]
df

,author,language,source
0,Sheikh Mahmoud Abdel Qader Hamz And Group Of S...,Afar,https://qurancomplex.gov.sa/
1,Tgk. H. Mahjiddin Jusuf,Achinese,https://www.islamic-invitation.com/
2,Imam M. A. Baker,Afrikaans,The Islamic Dawah Movement of Southern Africa
3,Muhammed Sadiq And Muhammed Sani Habib,Amharic,http://tanzil.net
4,Muhammed Sadiq And Muhammed Sani Habib,Amharic,http://tanzil.net
...,...,...,...
487,Ma Zhong Gang,Chinese(simplified),https://alquran.cloud/api
488,Muhammad Makin,Chinese(simplified),https://quranenc.com/check/chinese_makin/v1.0....
489,Muhammad Makin,Chinese(simplified),https://quranenc.com/check/chinese_makin/v1.0....
490,Muhammad Makin,Chinese(simplified),https://quranenc.com/check/chinese_makin/v1.0....
491,"Iqembu Lezifundiswa, Mussa Muhammad Telela , U...",Zulu,Islamic Dawah Movement of Southern Africa(IDM)...

In [10]:
import requests
URL2="https://www.scrapethissite.com/pages/simple/"
res=requests.get(URL2)

In [11]:
if res.status_code==200:
    #print(res.text)
    #print(res.content)
    print(res.headers)
with open("scraped data/data1.html","w",encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Fri, 11 Sep 2026 19:19:13 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=JQmUi%2FelacupZwmRfUgH29GHzJEE0axnOMwqGgJfQyA%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1789154353"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=JQmUi%2FelacupZwmRfUgH29GHzJEE0axnOMwqGgJfQyA%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1789154353"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': 'a39905d3fa8bf408-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [12]:
#working with beautiful soups
from bs4 import BeautifulSoup

with open("scraped data/data1.html", "r", encoding="utf-8") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [19]:
#soup.find("h1")
all_h3=soup.find_all("h3")
all_countries=[]
for h3 in all_h3:
    name=h3.get_text(strip=True)
    print(name)
    #print(h3.find_parent("div")["class"])
    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    print(population)
    all_countries.append([name,population])
    #print(h3.children) DOM
    #print(h3.parent)
    #print(h3.next_sibling)

Andorra
84000


United Arab Emirates
4975593


Afghanistan
29121286


Antigua and Barbuda
86754


Anguilla
13254


Albania
2986952


Armenia
2968000


Angola
13068161


Antarctica
0


Argentina
41343201


American Samoa
57881


Austria
8205000


Australia
21515754


Aruba
71566


Åland
26711


Azerbaijan
8303512


Bosnia and Herzegovina
4590000


Barbados
285653


Bangladesh
156118464


Belgium
10403000


Burkina Faso
16241811


Bulgaria
7148785


Bahrain
738004


Burundi
9863117


Benin
9056010


Saint Barthélemy
8450


Bermuda
65365


Brunei
395027


Bolivia
9947418


Bonaire
18012


Brazil
201103330


Bahamas
301790


Bhutan
699847


Bouvet Island
0


Botswana
2029307


Belarus
9685000


Belize
314522


Canada
33679000


Cocos [Keeling] Islands
628


Democratic Republic of the Congo
70916439


Central African Republic
4844927


Republic of the Congo
3039126


Switzerland
7581000


Ivory Coast
21058798


Cook Islands
21388


Chile
16746491


Cameroon
19294149


China
1330044000


Colombia
47790000


Costa Rica
4516220


Cuba
11423000


Cape Verde
508659


Curacao
141766


Christmas Island
1500


Cyprus
1102677


Czech Republic
10476000


Germany
81802257


Djibouti
740528


Denmark
5484000


Dominica
72813


Dominican Republic
9823821


Algeria
34586184


Ecuador
14790608


Estonia
1291170


Egypt
80471869


Western Sahara
273008


Eritrea
5792984


Spain
46505963


Ethiopia
88013491


Finland
5244000


Fiji
875983


Falkland Islands
2638


Micronesia
107708


Faroe Islands
48228


France
64768389


Gabon
1545255


United Kingdom
62348447


Grenada
107818


Georgia
4630000


French Guiana
195506


Guernsey
65228


Ghana
24339838


Gibraltar
27884


Greenland
56375


Gambia
1593256


Guinea
10324025


Guadeloupe
443000


Equatorial Guinea
1014999


Greece
11000000


South Georgia and the South Sandwich Islands
30


Guatemala
13550440


Guam
159358


Guinea-Bissau
1565126


Guyana
748486


Hong Kong
6898686


Heard Island and McDonald Islands
0


Honduras
7989415


Croatia
4491000


Haiti
9648924


Hungary
9982000


Indonesia
242968342


Ireland
4622917


Israel
7353985


Isle of Man
75049


India
1173108018


British Indian Ocean Territory
4000


Iraq
29671605


Iran
76923300


Iceland
308910


Italy
60340328


Jersey
90812


Jamaica
2847232


Jordan
6407085


Japan
127288000


Kenya
40046566


Kyrgyzstan
5776500


Cambodia
14453680


Kiribati
92533


Comoros
773407


Saint Kitts and Nevis
51134


North Korea
22912177


South Korea
48422644


Kuwait
2789132


Cayman Islands
44270


Kazakhstan
15340000


Laos
6368162


Lebanon
4125247


Saint Lucia
160922


Liechtenstein
35000


Sri Lanka
21513990


Liberia
3685076


Lesotho
1919552


Lithuania
2944459


Luxembourg
497538


Latvia
2217969


Libya
6461454


Morocco
31627428


Monaco
32965


Moldova
4324000


Montenegro
666730


Saint Martin
35925


Madagascar
21281844


Marshall Islands
65859


Macedonia
2062294


Mali
13796354


Myanmar [Burma]
53414374


Mongolia
3086918


Macao
449198


Northern Mariana Islands
53883


Martinique
432900


Mauritania
3205060


Montserrat
9341


Malta
403000


Mauritius
1294104


Maldives
395650


Malawi
15447500


Mexico
112468855


Malaysia
28274729


Mozambique
22061451


Namibia
2128471


New Caledonia
216494


Niger
15878271


Norfolk Island
1828


Nigeria
154000000


Nicaragua
5995928


Netherlands
16645000


Norway
5009150


Nepal
28951852


Nauru
10065


Niue
2166


New Zealand
4252277


Oman
2967717


Panama
3410676


Peru
29907003


French Polynesia
270485


Papua New Guinea
6064515


Philippines
99900177


Pakistan
184404791


Poland
38500000


Saint Pierre and Miquelon
7012


Pitcairn Islands
46


Puerto Rico
3916632


Palestine
3800000


Portugal
10676000


Palau
19907


Paraguay
6375830


Qatar
840926


Réunion
776948


Romania
21959278


Serbia
7344847


Russia
140702000


Rwanda
11055976


Saudi Arabia
25731776


Solomon Islands
559198


Seychelles
88340


Sudan
35000000


Sweden
9828655


Singapore
4701069


Saint Helena
7460


Slovenia
2007000


Svalbard and Jan Mayen
2550


Slovakia
5455000


Sierra Leone
5245695


San Marino
31477


Senegal
12323252


Somalia
10112453


Suriname
492829


South Sudan
8260490


São Tomé and Príncipe
175808


El Salvador
6052064


Sint Maarten
37429


Syria
22198110


Swaziland
1354051


Turks and Caicos Islands
20556


Chad
10543464


French Southern Territories
140


Togo
6587239


Thailand
67089500


Tajikistan
7487489


Tokelau
1466


East Timor
1154625


Turkmenistan
4940916


Tunisia
10589025


Tonga
122580


Turkey
77804122


Trinidad and Tobago
1228691


Tuvalu
10472


Taiwan
22894384


Tanzania
41892895


Ukraine
45415596


Uganda
33398682


U.S. Minor Outlying Islands
0


United States
310232863


Uruguay
3477000


Uzbekistan
27865738


Vatican City
921


Saint Vincent and the Grenadines
104217


Venezuela
27223228


British Virgin Islands
21730


U.S. Virgin Islands
108708


Vietnam
89571130


Vanuatu
221552


Wallis and Futuna
16025


Samoa
192001


Kosovo
1800000


Yemen
23495361


Mayotte
159042


South Africa
49000000


Zambia
13460305


Zimbabwe
11651858

In [14]:
import pandas as pd
df=pd.DataFrame(all_countries,columns=["country","population"])

In [15]:
df.to_csv("Cleaned Data/data.csv")

                  country population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]